"""
The LLM Report — Buttondown Newsletter Publisher
Publishes newsletter drafts to Buttondown API.
Draft mode: always True in Phase 1 (Boss reviews first few before enabling auto-send).
NLSpec Section 5.5, Scenario 5.5
"""

from __future__ import annotations
import os
import re
import time
from typing import Optional

import requests

BUTTONDOWN_API_URL = "https://api.buttondown.email/v1"
BUTTONDOWN_API_KEY = os.environ.get("BUTTONDOWN_API_KEY", "")

EMAIL_FOOTER = """
<hr style="border:none;border-top:1px solid #e0e0e0;margin:2rem 0;">
<p style="font-size:13px;color:#666;line-height:1.6;">
  <strong>The LLM Report</strong> is autonomously generated by AI.
  Read-only newsletter — no replies monitored.
  Contact: <a href="mailto:aifactory.ops@outlook.com">aifactory.ops@outlook.com</a>
  <br>
  AI Factory Operations · c/o Vit · Minneapolis, MN, USA
  <br>
  <a href="{{unsubscribe_url}}">Unsubscribe</a> · <a href="https://thellmreport.com">View online</a>
</p>
"""


def markdown_to_html(markdown_text: str) -> str:
    """Convert newsletter markdown to HTML suitable for email."""
    try:
        import markdown
        html = markdown.markdown(
            markdown_text,
            extensions=["tables", "fenced_code"],
        )
    except ImportError:
        # Fallback: basic markdown conversion
        html = markdown_text
        html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
        html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
        html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)
        html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
        html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)
        html = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', html)
        html = "<br>".join(html.split("\n"))

    # Wrap in email-safe container
    styled_html = f"""
<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;
            max-width:600px;margin:0 auto;padding:20px;color:#1a1a1a;line-height:1.7;font-size:16px;">
  <div style="border-bottom:2px solid #1a1a8c;padding-bottom:12px;margin-bottom:24px;">
    <strong style="font-size:1.2rem;">The LLM Report</strong>
  </div>
  {html}
  {EMAIL_FOOTER}
</div>
"""
    return styled_html


def publish_newsletter_draft(
    subject: str,
    html_body: str,
    edition_date: str,
    topics: list[str] | None = None,
    draft: bool = True,
    api_key: Optional[str] = None,
) -> dict:
    """
    Create a draft email in Buttondown.

    Args:
        subject: Email subject line
        html_body: HTML email body
        edition_date: Edition date (YYYY-MM-DD) for tagging
        topics: Content topics for subscriber tagging
        draft: Always True in Phase 1
        api_key: Override API key (for testing)

    Returns:
        dict with: email_id, status, subject, draft
    """
    key = api_key or BUTTONDOWN_API_KEY
    if not key:
        raise ValueError("BUTTONDOWN_API_KEY not set")

    headers = {
        "Authorization": f"Token {key}",
        "Content-Type": "application/json",
    }

    payload = {
        "subject": subject,
        "body": html_body,
        "status": "draft" if draft else "about_to_send",
        "email_type": "public",
    }

    # Retry once on 5xx errors
    last_error = None
    for attempt in range(2):
        try:
            resp = requests.post(
                f"{BUTTONDOWN_API_URL}/emails",
                json=payload,
                headers=headers,
                timeout=30,
            )
            if resp.status_code in (200, 201):
                data = resp.json()
                return {
                    "email_id": data.get("id", ""),
                    "status": data.get("status", "draft"),
                    "subject": subject,
                    "draft": draft,
                }
            elif resp.status_code >= 500 and attempt == 0:
                time.sleep(2)
                continue
            else:
                raise RuntimeError(
                    f"Buttondown API returned {resp.status_code}: {resp.text[:200]}"
                )
        except requests.RequestException as e:
            last_error = e
            if attempt == 0:
                time.sleep(2)

    raise RuntimeError(f"Buttondown API failed after retries: {last_error}")


def build_subject(edition_date: str) -> str:
    """Build the email subject for a given edition date."""
    return f"The LLM Report \u2014 {edition_date}"
